import Link from "next/link";
const Check=()=> <span className="lpCheck">✓</span>;
export default function Page(){return <main className="landing">
<nav className="lpNav"><Link href="/" className="lpBrand">HOLD<span>MASTO</span></Link><div className="lpNavLinks"><a href="#fonctionnement">Comment ça marche</a><a href="#tarifs">Tarifs</a><Link className="lpLogin" href="/login">Connexion</Link><a className="lpBtn smallBtn" href="#demo">Tester Léa</a></div></nav>
<section className="lpHero"><div className="lpEyebrow">STANDARD TÉLÉPHONIQUE & SUIVI COMMERCIAL</div><h1>Ne perdez plus un chantier parce que <em>vous n’avez pas répondu.</em></h1><p className="lpLead">Léa accueille vos prospects quand vous êtes sur un chantier, comprend leur demande, la qualifie et prépare la suite — sans vous interrompre.</p><div className="lpActions"><a className="lpBtn" href="#demo">Parler avec Léa <b>→</b></a><a className="lpGhost" href="#fonctionnement">Voir comment ça marche</a></div><p className="lpMicro">Démonstration immédiate · Aucun engagement · Testez comme si vous étiez un client</p>
<div className="lpProof"><div><strong>24/7</strong><span>Accueil des demandes</span></div><div><strong>&lt; 1 min</strong><span>Première réponse</span></div><div><strong>1 tableau</strong><span>Pour suivre les opportunités</span></div></div></section>
<section className="lpPain"><p className="lpKicker">LE PROBLÈME</p><h2>Vous travaillez. Le téléphone sonne.<br/>Le prospect appelle le suivant.</h2><div className="lpPainGrid"><article><b>01</b><h3>Appel manqué</h3><p>Vous êtes en intervention, au volant ou avec un client. Impossible de décrocher.</p></article><article><b>02</b><h3>Demande perdue</h3><p>Le prospect veut une réponse maintenant. Il contacte une autre entreprise.</p></article><article><b>03</b><h3>Chiffre d’affaires perdu</h3><p>Vous ne savez même pas quelle opportunité vous venez de laisser passer.</p></article></div></section>
<section id="fonctionnement" className="lpHow"><div><p className="lpKicker">AVEC HOLDMASTO</p><h2>Léa prend le relais.<br/>Vous gardez le contrôle.</h2><p className="lpLead compact">Chaque demande est accueillie, structurée et visible dans votre espace Holdmasto.</p></div><div className="lpSteps"><article><span>1</span><div><h3>Le prospect contacte votre entreprise</h3><p>Léa répond avec le nom et le contexte de votre société.</p></div></article><article><span>2</span><div><h3>Elle comprend et qualifie le besoin</h3><p>Urgence, type d’intervention, localisation et informations utiles.</p></div></article><article><span>3</span><div><h3>Vous récupérez une demande exploitable</h3><p>Le prospect et son besoin arrivent dans votre pipeline commercial.</p></div></article></div></section>
<section id="demo" className="lpDemo"><div className="lpDemoCopy"><p className="lpKicker">LA PREUVE, PAS LE DISCOURS</p><h2>Mettez-vous à la place de votre prochain client.</h2><p>Testez Léa maintenant. Dites-lui par exemple que vous avez une fuite importante, une panne de chauffage ou besoin d’un devis.</p><div className="lpTicks"><p><Check/> Une seule question utile à la fois</p><p><Check/> Qualification naturelle de la demande</p><p><Check/> Démonstration sans engagement</p></div></div><div className="lpPhone"><div className="lpPhoneTop"><span className="lpAvatar">L</span><div><b>Léa</b><small>Assistante d’accueil</small></div><i>● Disponible</i></div><div className="lpBubble">Bonjour, je suis Léa, l’assistante d’accueil. Comment puis-je vous aider aujourd’hui ?</div><div className="lpBubble userBubble">Bonjour, j’ai une fuite importante et je suis sur un chantier.</div><div className="lpBubble">D’accord. Pouvez-vous couper l’arrivée générale d’eau actuellement ?</div><Link href="/login" className="lpBtn demoBtn">Tester une démonstration →</Link></div></section>
<section className="lpUse"><p className="lpKicker">CONÇU POUR LE TERRAIN</p><h2>Holdmasto s’adapte à votre activité.</h2><div className="lpUseGrid"><article><span>🔧</span><h3>Plomberie & chauffage</h3><p>Urgences, pannes, devis et interventions.</p></article><article><span>⚡</span><h3>Électricité</h3><p>Pannes, installations et demandes de devis.</p></article><article><span>🏠</span><h3>Rénovation & toiture</h3><p>Qualification des projets avant rappel.</p></article><article><span>🚗</span><h3>Garage & transport</h3><p>Demandes, disponibilités et prise de contact.</p></article></div></section>
<section id="tarifs" className="lpPricing"><p className="lpKicker">DES OFFRES SIMPLES</p><h2>Une demande sauvée peut déjà rentabiliser le mois.</h2><div className="lpPriceGrid"><article><h3>Essentiel</h3><strong>199 €<small>/mois</small></strong><p>+ 490 € de mise en place</p><ul><li><Check/>Accueil des demandes</li><li><Check/>Qualification</li><li><Check/>Tableau de suivi</li></ul><a href="#demo" className="lpGhost full">Tester Léa</a></article><article className="featured"><div className="popular">LE PLUS ADAPTÉ AUX ARTISANS</div><h3>Pro</h3><strong>399 €<small>/mois</small></strong><p>+ 990 € de mise en place</p><ul><li><Check/>Tout Essentiel</li><li><Check/>Relances commerciales</li><li><Check/>Pipeline & suivi avancé</li><li><Check/>Personnalisation métier</li></ul><a href="#demo" className="lpBtn full">Voir Léa en action</a></article><article><h3>Business</h3><strong>699 €<small>/mois</small></strong><p>+ 1 490 € de mise en place</p><ul><li><Check/>Tout Pro</li><li><Check/>Équipe & volumes supérieurs</li><li><Check/>Accompagnement avancé</li></ul><a href="#demo" className="lpGhost full">Tester Léa</a></article></div></section>
<section className="lpFinal"><p className="lpKicker">VOTRE PROCHAIN PROSPECT PEUT APPELER PENDANT QUE VOUS LISEZ CECI</p><h2>Voyez ce que Léa lui répondrait.</h2><a className="lpBtn big" href="#demo">Tester Léa maintenant →</a><p>Aucune carte bancaire · Démonstration immédiate</p></section>
<footer className="lpFooter"><span className="lpBrand">HOLD<span>MASTO</span></span><p>Transformez les demandes manquées en opportunités commerciales.</p><Link href="/login">Connexion</Link></footer>
</main>}