"use client";
import {useEffect,useState} from "react";import {useParams,useRouter} from "next/navigation";import Shell from "@/components/Shell";import {createClient} from "@/lib/supabase/client";
const statuses=["to_contact","contacted","replied","qualified","meeting","demo","proposal","won","lost","do_not_contact"];
export default function Page(){const {id}=useParams<{id:string}>();const router=useRouter();const [p,setP]=useState<any>(null),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push("/login");return}const {data}=await s.from("prospects").select("*").eq("id",id).single();setP(data);setDraft(data?.ai_pitch||"")}
useEffect(()=>{load()},[id]);
async function update(patch:any){const s=createClient();const {error}=await s.from("prospects").update(patch).eq("id",id);if(error)setMsg(error.message);else{setP({...p,...patch});setMsg("Enregistre.")}}
async function generate(){setBusy(true);const r=await fetch("/api/ai/pitch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prospect:p})});const d=await r.json();setDraft(d.text||"");await update({ai_pitch:d.text||""});setBusy(false)}
async function saveDraft(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from("messages").insert({user_id:user.id,prospect_id:id,channel:"email",direction:"outbound",body:draft,status:"draft"});setMsg(error?error.message:"Brouillon ajoute a l'historique.")}
if(!p)return <Shell><p className="muted">Chargement...</p></Shell>;
return <Shell><header className="top"><div><h1>{p.name}</h1><p className="muted">{p.address}</p></div><span className="score">{p.score}/100</span></header><div className="grid"><section className="panel"><h2>Closing</h2><label>Etape<select value={p.status} onChange={e=>update({status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>MRR estime<input type="number" value={p.estimated_mrr||0} onChange={e=>setP({...p,estimated_mrr:Number(e.target.value)})} onBlur={()=>update({estimated_mrr:p.estimated_mrr||0})}/></label><label>Notes<textarea value={p.notes||""} onChange={e=>setP({...p,notes:e.target.value})} onBlur={()=>update({notes:p.notes||""})}/></label><p>{p.phone||"Pas de telephone"}</p>{p.website&&<a className="webLink" href={p.website} target="_blank">Ouvrir le site</a>}</section><section className="panel"><h2>Message commercial</h2><button className="btn" onClick={generate} disabled={busy}>{busy?"Generation...":"Generer avec IA"}</button><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Le message apparaitra ici."/><button className="chip active" onClick={saveDraft}>Enregistrer le brouillon</button>{msg&&<p className="success">{msg}</p>}</section></div></Shell>}