"use client";
import {useEffect,useState} from "react";import {useParams,useRouter} from "next/navigation";import Shell from "@/components/Shell";import {createClient} from "@/lib/supabase/client";
const statuses=["to_contact","contacted","replied","qualified","meeting","demo","proposal","won","lost","do_not_contact"];
export default function Page(){const {id}=useParams<{id:string}>();const router=useRouter();const [p,setP]=useState<any>(null),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[enriching,setEnriching]=useState(false),[msg,setMsg]=useState(""),[meeting,setMeeting]=useState(""),[demo,setDemo]=useState<any>(null);
async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push("/login");return}const {data}=await s.from("prospects").select("*").eq("id",id).single();setP(data);setDraft(data?.ai_pitch||"");const {data:existing}=await s.from("demos").select("*").eq("prospect_id",id).maybeSingle();setDemo(existing)}
useEffect(()=>{load()},[id]);
async function activity(type:string,description:string){const s=createClient();const {data:{user}}=await s.auth.getUser();if(user)await s.from("activities").insert({user_id:user.id,prospect_id:id,campaign_id:p.campaign_id,type,description})}
async function update(patch:any){const s=createClient();const {error}=await s.from("prospects").update(patch).eq("id",id);if(error)setMsg(error.message);else{setP({...p,...patch});setMsg("Enregistre.");if(patch.status)await activity("status_change","Etape: "+patch.status)}}
async function generate(){const base=(process.env.NEXT_PUBLIC_APP_URL||"https://holdmasto.vercel.app").replace(/\/$/,"");if(!base){setMsg("Configure NEXT_PUBLIC_APP_URL avec le domaine public Holdmasto avant de generer un email.");return}setBusy(true);const r=await fetch("/api/ai/pitch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prospect:p,demoUrl:demo?base+"/demo/"+demo.slug:null,assistantName:"Lea"})});const d=await r.json();setDraft(d.text||"");await update({ai_pitch:d.text||""});setBusy(false)}
async function enrichProspect(){setEnriching(true);setMsg("");try{const r=await fetch("/api/prospects/"+id+"/enrich",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Enrichissement impossible");setP(d.prospect);setMsg("Prospect enrichi. Confiance: "+d.prospect.enrichment_confidence+"/100");}catch(e){setMsg(e instanceof Error?e.message:"Enrichissement impossible");}finally{setEnriching(false)}}
async function saveDraft(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from("messages").insert({user_id:user.id,prospect_id:id,channel:"email",direction:"outbound",body:draft,status:"draft"});if(!error)await activity("draft_created","Brouillon commercial cree");setMsg(error?error.message:"Brouillon ajoute a l'historique.")}
async function addMeeting(){if(!meeting)return;const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const start=new Date(meeting);const {error}=await s.from("appointments").insert({user_id:user.id,prospect_id:id,title:"Demo Holdmasto - "+p.name,starts_at:start.toISOString(),ends_at:new Date(start.getTime()+30*60000).toISOString()});if(!error){await update({status:"meeting",next_action_at:start.toISOString()});setMsg("RDV enregistre.")}else setMsg(error.message)}

async function createDemo(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const slug=(p.name||"prospect").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")+"-"+id.slice(0,6);const payload={user_id:user.id,prospect_id:id,slug,business_name:p.name,business_type:p.legal_name||"Entreprise locale",city:p.address||"",phone:p.phone,website:p.website,agent_name:"Lea",welcome_message:"Bonjour, je suis Lea, l'assistante d'accueil de "+p.name+". Comment puis-je vous aider aujourd'hui ?",agent_goal:"Comprendre la demande, qualifier le besoin et proposer une prise de contact",system_prompt:"Tu representes "+p.name+". Tu accueilles un client potentiel, comprends son besoin, poses une seule question utile a la fois et proposes une prise de contact. Ne pretend jamais qu'une action reelle a ete effectuee : ceci est une demonstration."};const {data,error}=await s.from("demos").upsert(payload,{onConflict:"user_id,prospect_id"}).select().single();if(error){setMsg(error.message);return}setDemo(data);await update({status:"demo"});setMsg("Demo 1:1 creee.")}
if(!p)return <Shell><p className="muted">Chargement...</p></Shell>;
const publicBase=(process.env.NEXT_PUBLIC_APP_URL||"https://holdmasto.vercel.app").replace(/\/$/,"");const demoUrl=demo&&publicBase?publicBase+"/demo/"+demo.slug:"";const emailBody=draft+(demoUrl&&!draft.includes(demoUrl)?"\n\nTester votre demonstration personnalisee : "+demoUrl:"");const mailHref=p.email?`mailto:${p.email}?subject=${encodeURIComponent("Une demonstration preparee pour "+p.name)}&body=${encodeURIComponent(emailBody)}`:"";
return <Shell><header className="top"><div><h1>{p.name}</h1><p className="muted">{p.address}</p></div><span className="score">{p.score}/100</span></header><div className="grid"><section className="panel"><h2>Closing</h2><label>Etape<select value={p.status} onChange={e=>update({status:e.target.value})}>{statuses.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>MRR estime<input type="number" value={p.estimated_mrr||0} onChange={e=>setP({...p,estimated_mrr:Number(e.target.value)})} onBlur={()=>update({estimated_mrr:p.estimated_mrr||0})}/></label><label>Notes<textarea value={p.notes||""} onChange={e=>setP({...p,notes:e.target.value})} onBlur={()=>update({notes:p.notes||""})}/></label><p>{p.phone||"Pas de telephone"} · {p.email||"Email non detecte"}</p>{p.website&&<a className="webLink" href={p.website} target="_blank" rel="noreferrer">Ouvrir le site</a>}<h3>Enrichissement</h3><button className="btn" onClick={enrichProspect} disabled={enriching}>{enriching?"Recherche en cours...":"Enrichir le prospect"}</button><p className="mini">Statut: {p.enrichment_status||"pending"} · Confiance: {p.enrichment_confidence||0}/100</p>{(p.contact_first_name||p.contact_last_name)&&<p><b>{[p.contact_first_name,p.contact_last_name].filter(Boolean).join(" ")}</b>{p.contact_role?" · "+p.contact_role:""}</p>}{p.linkedin_url&&<a className="webLink" href={p.linkedin_url} target="_blank" rel="noreferrer">Voir LinkedIn</a>}{p.enrichment_summary&&<p className="muted">{p.enrichment_summary}</p>}<h3>Demo 1:1</h3><div className="filters"><button className="btn" onClick={createDemo}>{demo?"Regenerer la demo":"Creer sa demo"}</button>{demo&&<a className="chip active" href={"/demo/"+demo.slug} target="_blank" rel="noreferrer">Tester la demo</a>}</div>{demo&&<p className="mini">Lien: /demo/{demo.slug}</p>}<h3>Planifier une demo</h3><input type="datetime-local" value={meeting} onChange={e=>setMeeting(e.target.value)}/><button className="chip active" onClick={addMeeting}>Ajouter le RDV</button></section><section className="panel"><h2>Message commercial</h2><button className="btn" onClick={generate} disabled={busy}>{busy?"Generation...":"Generer le message"}</button><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Le message apparaitra ici."/><div className="filters"><button className="chip active" onClick={saveDraft}>Enregistrer le brouillon</button>{p.email&&draft&&demoUrl&&<a className="btn" href={mailHref} onClick={()=>activity("email_opened","Email prepare pour envoi")}>Ouvrir dans mon email</a>}</div>{msg&&<p className="success">{msg}</p>}</section></div></Shell>}